### ISSUE TITLE
Reloading website pages leads to a 404

### ISSUE THREAD

**Issue by soenkehahn** [garnix-io/garn#250]
When you go to https://garn.io and then navigate to another page on the website, it works at first. But reloading any page (e.g. https://garn.io/docs/getting_started) will result in a 404.

**Comment by jkarni** [comment]
For me it’s *just* the getting started page. And I’m pretty sure it’s
because we aren’t pre-rendering it. (There’s a list of to-be pre-rendered
pages in the vote config)

We should *also* make the 404 page be our index.html, which I think would
fix this issue as well as others.

**Comment by soenkehahn** [comment]
Ah, thanks. Put up #252 for this.
