### ISSUE TITLE
Redo landing page to include clearer description

### ISSUE THREAD

**Issue by jkarni** [garnix-io/garn#281]
Explain what `garn` is. Immediately.

Maybe something along the lines of:

garn is a build tool and environment manager. It can in part or wholly replace manual README instructions, containerization technologies like docker, package managers such as apt/brew/yam/etc, and just/make. You configure your project in Typescript, which provides for great discoverability through auto-completion and type errors, as well as facilities for abstraction and easy sharing of code.

**Comment by soenkehahn** [comment]
This should mention the supported languages / toolchains.
