### ISSUE TITLE
Getting rid of nix’s git staging requirements

### ISSUE THREAD

**Issue by jkarni** [garnix-io/garn#314]
It’s incredibly annoying that unstaged files get ignored, and that we get warnings every time the tree is dirty. We should fix this somehow. I think only gitignored files should be ignored.

I think potentially we could upstream this to nix. Or we could fork nix.

**Comment by jfroche** [comment]
changing https://github.com/domenkozar/nix/commit/bf9922e7b21b83450006640d2382e04e5a203692#diff-4de86ddf9ae3dd43a49cc14cc56e2f6b29f51fde7a0603e3ab7c5cd34599b5d7R395 to something which include:

`git ls-files --cached -z --others --exclude-from=.gitignore` seem to do the trick but only takes into account the root .gitignore

**Comment by alexdavid** [comment]
There seems to be `--exclude-standard` which handles nested `.gitignore` files.

**Comment by jfroche** [comment]
I have opened the PR into nix https://github.com/NixOS/nix/pull/9352
Someone else opened a similar (but not optional) change and got this reply from the nix team: https://github.com/NixOS/nix/pull/6858#issuecomment-1666156844 but at least this new PR is opt-in
I will add it into garn tomorrow

**Comment by jfroche** [comment]
Garn PR: https://github.com/garnix-io/garn/pull/406
