### ISSUE TITLE
Export `pkgs.nodePackages` (for e.g. `prettier`) in `nixpkgs.ts`

### ISSUE THREAD

**Issue by soenkehahn** [garnix-io/garn#339]

**Comment by jkarni** [comment]
How will this work? Will it be exported as a nested record? (It feels like we can’t export all these packages as the top level without a big risk of conflict.)

**Comment by alexdavid** [comment]
The implementation I have in #382 breaks each sub package up into its own file and uses `export * from "..."`. This way `pkgs` matches as close as possible to the real nixpkgs in terms of structure, and we don't have conflicts.
