### ISSUE TITLE
Disable file and network access when running the garn file

### ISSUE THREAD

**Issue by jkarni** [garnix-io/garn#448]
There are lots of problems with allowing it, like `--help` hanging and project structure being potentially not deterministic. From a quick look, it looks like the only offender preventing that right now is `go`, and there's no reason not to inline the call into the derivation.

This only applies to the normal runner. `init` should be free to use whatever it wants.

**Comment by soenkehahn** [comment]
We can't disable network access when running `gomod2nix`, it *has* to download  go package hashes.
