### ISSUE TITLE
Handle untracked flake files elegantly

### ISSUE THREAD

**Issue by jkarni** [garnix-io/garn#62]
`garner` commands usually (re)generate a `flake.nix`, and then uses that. If, however, the `flake.nix` is untracked (as usually it will be the first time around), nix complains about a non-existent `flake.nix` - which is very confusing.

Find a nicer system for this. For example:

- Warn that `flake.nix` must be added
- Automatically `git add --intent-to-add` the `flake.nix` file.

**Comment by soenkehahn** [comment]
Fixed in #214.
